### ISSUE TITLE
Analiza - błąd w definicji granicy iterowanej

### ISSUE THREAD

**Issue by kkawula** [mdbrnowski/notes#3]
Strona 24 - zduplikowany wzór

**Comment by mdbrnowski** [comment]
@taylor-swif Jeśli chodzi o tę uwagę na stronie 24 (o przykładzie 4.6) to nie jest to błąd. Zauważ, że środkowe przekształcenie się różni. Wynika to z tego, że w zależności od tego, czy $\varphi = \pm \frac{\pi}{2}$, czy nie, inny składnik sumy w mianowniku się zeruje, więc inaczej się liczy granicę, która i tak w końcu wyjdzie równa 0.

**Comment by kkawula** [comment]
Mogłem opisać to trochę dokładniej, chodziło mi o wzór na granice iterowaną

**Comment by mdbrnowski** [comment]
A, rzeczywiście, poprawię dzisiaj.
